services:
    db:
        container_name: db
        image: bendereg/postgres_memo
        env_file:
            - .env
        volumes:
            - memo_db_new:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d/
        networks:
            - app
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always

    red:
        container_name: red
        image: redis
        volumes:
            - test_red:/data
        networks:
            - app
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5
        restart: always

    memo_main:
        container_name: memo_main
        build: .
        depends_on:
            - db
            - red
        env_file:
            - .env
        networks:
            - app
        restart: always

volumes:
    memo_db_new:
        name: memo_db_new
    test_red:
        name: test_red

networks:
    app:
        name: app
