services:
    db:
        container_name: db
        image: postgres:latest
        env_file:
            - .env
        ports:
            - 5433:5432
        volumes:
            - memo_postgres:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d/
        networks:
            - memo_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5

    red:
        container_name: red
        image: redis
        volumes:
            - memo_redis:/data
        ports:
            - 6379:6379
        networks:
            - memo_net
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 1s
            timeout: 3s
            retries: 5

volumes:
    memo_postgres:
        name: memo_postgres
    memo_redis:
        name: memo_redis

networks:
    memo_net:
        name: memo_net
