[tool.poetry]
name = "telebotmemo"
version = "0.1.0"
description = "telegram bot for memoization"
authors = ["egor nikitin <eanikitin90gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
redis = "^4.6.0"
psycopg2 = "^2.9.6"
apscheduler = "^3.10.1"
flake8 = "^6.1.0"
sortedcontainers = "^2.4.0"
sqlalchemy = "^2.0.23"
asyncpg = "^0.29.0"
pydantic-settings = "^2.0.3"
alembic = "^1.12.1"
black = "^23.11.0"
aiogram3-di = "^1.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
